# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 897939d5a05a2f0fee277254dc1a1514a957f2091dfeb830f8a3499e1a513ece09cd1c398ec9ec1d07fa31410b733da4b80d1d8233c1496fb304c32f5b64e51f

test:
  secret_key_base: c023c95efcc5b9bb08b05821c9b57d4ff2742222e42a8199acc93f3b973ca59af0787d813cb530f7ca77c10c032c4be21fbe1ead66e1c2ee028a4404d527d75f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
